<?php
session_start();
require '../../includes/conexao.php';
require '../../includes/verificar_sessao.php';
verificar_perfil('Aluno');
$id_aluno = $_SESSION['id_usuario'];
$questionarios = [];
$sql = 'SELECT q.id_questionario,q.titulo,q.descricao,q.data_criacao,CASE WHEN COUNT(r.id_resposta)>0 THEN 1 ELSE 0 END AS respondido FROM questionario q LEFT JOIN pergunta p ON p.id_questionario=q.id_questionario LEFT JOIN resposta r ON r.id_pergunta=p.id_pergunta AND r.id_usuario=? GROUP BY q.id_questionario,q.titulo,q.descricao,q.data_criacao ORDER BY q.data_criacao DESC';
$stmt=$conexao->prepare($sql);$stmt->bind_param('i',$id_aluno);$stmt->execute();$result=$stmt->get_result();while($row=$result->fetch_assoc()){$questionarios[]=$row;}$stmt->close();
$pendentes=array_filter($questionarios,fn($q)=>(int)$q['respondido']===0);$respondidos=array_filter($questionarios,fn($q)=>(int)$q['respondido']===1);
function lista_questionarios($lista){if(!$lista){echo '<p style="color:#666">Nenhum questionário nesta categoria.</p>';return;}foreach($lista as $q){echo '<a class="item" href="questionario_aluno.php?id='.(int)$q['id_questionario'].'"><h3>'.htmlspecialchars($q['titulo']).'</h3><p>'.htmlspecialchars($q['descricao']??'').'</p><small>'.date('d/m/Y',strtotime($q['data_criacao'])).'</small></a>';}}
?>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Aluno | Questionários</title><style>*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f3f6fb;color:#1f2937}main{max-width:1080px;margin:32px auto;padding:0 20px 40px}.cabecalho{background:linear-gradient(135deg,#1f3b65,#4568a8);color:#fff;border-radius:18px;padding:26px 28px;margin-bottom:24px}.cabecalho h1{margin:0;font-size:2rem}.panel{background:#fff;border:1px solid #e2eaf5;border-radius:18px;padding:22px;margin-bottom:20px;box-shadow:0 8px 20px rgba(15,23,42,.04)}.panel h2{margin-top:0;color:#133b6d}.lista{display:grid;gap:14px}.item{display:block;background:#fff;border:1px solid #e2eaf5;border-radius:14px;padding:18px 20px;text-decoration:none;color:#1f2937;box-shadow:0 7px 18px rgba(15,23,42,.04)}.item h3{margin:0 0 7px;color:#123d70;font-size:1.15rem}.item p{margin:4px 0;color:#657286}.badge{display:inline-block;padding:5px 9px;border-radius:999px;font-size:.72rem;font-weight:bold;background:#fff4e5;color:#996000}</style></head><body><?php include '../../includes/menu_aluno.php';?><main><section class="cabecalho"><h1>Questionários</h1></section><section class="panel"><h2>Pendentes</h2><div class="lista"><?php lista_questionarios($pendentes);?></div></section><section class="panel"><h2>Respondidos</h2><div class="lista"><?php lista_questionarios($respondidos);?></div></section></main></body></html>
