<?php
session_start();
require '../../includes/conexao.php';
require '../../includes/verificar_sessao.php';
verificar_perfil('Secretaria');
mysqli_report(MYSQLI_REPORT_OFF);
$tipos=['aluno'=>'Aluno','professor'=>'Professor','coordenacao'=>'Coordenação','secretaria'=>'Secretaria','turma'=>'Turma','disciplina'=>'Disciplina'];
$tipo=strtolower(trim($_GET['tipo']??$_POST['tipo']??''));$acao=strtolower(trim($_GET['acao']??$_POST['acao']??'deletar'));$id=intval($_GET['id']??$_POST['id']??0);$turma_origem=intval($_GET['turma']??$_POST['turma']??0);
if(!isset($tipos[$tipo])||$id<=0){header('Location: cadastros_secretaria.php');exit();}$mensagem='';
function executar($conexao,$sql,$tipos,$valores){$stmt=$conexao->prepare($sql);if(!$stmt)return false;$stmt->bind_param($tipos,...$valores);$ok=$stmt->execute();$stmt->close();return $ok;}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['confirmar'])){
    $conexao->begin_transaction();$ok=true;
    if($tipo==='aluno'){
        $stmt=$conexao->prepare('SELECT id_matricula FROM matricula WHERE id_aluno=?');$stmt->bind_param('i',$id);$stmt->execute();$result=$stmt->get_result();$ids=[];while($row=$result->fetch_assoc())$ids[]=(int)$row['id_matricula'];$stmt->close();
        foreach($ids as $id_matricula){$ok=executar($conexao,'DELETE FROM frequencia WHERE id_matricula=?','i',[$id_matricula])&&$ok;$ok=executar($conexao,'DELETE FROM nota WHERE id_matricula=?','i',[$id_matricula])&&$ok;}
        $ok=executar($conexao,'DELETE FROM resposta WHERE id_usuario=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM mensagem WHERE remetente=? OR destinatario=?','ii',[$id,$id])&&$ok;$ok=executar($conexao,'DELETE FROM matricula WHERE id_aluno=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM usuario WHERE id_usuario=? AND perfil="Aluno"','i',[$id])&&$ok;
    } elseif($tipo==='turma'){
        $stmt=$conexao->prepare('SELECT id_turma_disciplina FROM turma_disciplina WHERE id_turma=?');$stmt->bind_param('i',$id);$stmt->execute();$result=$stmt->get_result();$ids=[];while($row=$result->fetch_assoc())$ids[]=(int)$row['id_turma_disciplina'];$stmt->close();
        foreach($ids as $id_td){$ok=executar($conexao,'DELETE FROM horario WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM frequencia WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM nota WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;}
        $ok=executar($conexao,'DELETE FROM turma_disciplina WHERE id_turma=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM matricula WHERE id_turma=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM turma WHERE id_turma=?','i',[$id])&&$ok;
    } elseif($tipo==='disciplina'){
        $stmt=$conexao->prepare('SELECT id_turma_disciplina FROM turma_disciplina WHERE id_disciplina=?');$stmt->bind_param('i',$id);$stmt->execute();$result=$stmt->get_result();$ids=[];while($row=$result->fetch_assoc())$ids[]=(int)$row['id_turma_disciplina'];$stmt->close();
        foreach($ids as $id_td){$ok=executar($conexao,'DELETE FROM horario WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM frequencia WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM nota WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;}
        $ok=executar($conexao,'DELETE FROM turma_disciplina WHERE id_disciplina=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM professor_disciplina WHERE id_disciplina=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM disciplina WHERE id_disciplina=?','i',[$id])&&$ok;
    } elseif($tipo==='professor'){
        $stmt=$conexao->prepare('SELECT id_turma_disciplina FROM turma_disciplina WHERE id_professor=?');$stmt->bind_param('i',$id);$stmt->execute();$result=$stmt->get_result();$ids=[];while($row=$result->fetch_assoc())$ids[]=(int)$row['id_turma_disciplina'];$stmt->close();
        foreach($ids as $id_td){$ok=executar($conexao,'DELETE FROM horario WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM frequencia WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM nota WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;}
        $ok=executar($conexao,'DELETE FROM turma_disciplina WHERE id_professor=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM professor_disciplina WHERE id_professor=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM mensagem WHERE remetente=? OR destinatario=?','ii',[$id,$id])&&$ok;$ok=executar($conexao,'DELETE FROM usuario WHERE id_usuario=? AND perfil="Professor"','i',[$id])&&$ok;
    } else {
        $perfil=$tipos[$tipo];$ok=executar($conexao,'DELETE FROM mensagem WHERE remetente=? OR destinatario=?','ii',[$id,$id])&&$ok;$ok=executar($conexao,'DELETE FROM usuario WHERE id_usuario=? AND perfil=?','is',[$id,$perfil])&&$ok;
    }
    if($ok){$conexao->commit();header('Location: consultas_secretaria.php?tipo='.urlencode($tipo).'&acao='.urlencode($acao).($turma_origem?'&turma='.$turma_origem:''));exit();}$conexao->rollback();$mensagem='<div class="erro">Não foi possível excluir. Existem dados relacionados que não podem ser removidos automaticamente.</div>';
}
if($tipo==='aluno'){$stmt=$conexao->prepare('SELECT u.nome,u.email,m.rm,t.nome AS turma_nome FROM usuario u LEFT JOIN matricula m ON m.id_aluno=u.id_usuario LEFT JOIN turma t ON t.id_turma=m.id_turma WHERE u.id_usuario=? AND u.perfil="Aluno"');}elseif(in_array($tipo,['professor','coordenacao','secretaria'],true)){$stmt=$conexao->prepare('SELECT nome,email,perfil FROM usuario WHERE id_usuario=? AND perfil=?');$perfil=$tipos[$tipo];$stmt->bind_param('is',$id,$perfil);}elseif($tipo==='turma'){$stmt=$conexao->prepare('SELECT nome,ano_letivo,periodo FROM turma WHERE id_turma=?');}else{$stmt=$conexao->prepare('SELECT nome,carga_horaria FROM disciplina WHERE id_disciplina=?');}if($tipo==='aluno'||$tipo==='turma'||$tipo==='disciplina')$stmt->bind_param('i',$id);$stmt->execute();$registro=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$registro){header('Location: consultas_secretaria.php?tipo='.urlencode($tipo).'&acao='.urlencode($acao));exit();}
?>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Secretaria | Deletar</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>
*{box-sizing:border-box}body{margin:0;background:#f7f8fc;color:#202338;font-family:Inter,Arial,sans-serif}main{max-width:1110px;margin:0 auto;padding:44px 36px 70px}h1,h2{letter-spacing:-.04em}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #b6b4ff;outline-offset:2px}.header{background:none;color:#202338;padding:0;margin:0 0 26px;border-radius:0}.header:before{content:'INSTITUTO ATLAS / SECRETARIA';display:block;color:#6664df;font-size:11px;font-weight:800;letter-spacing:.14em;margin-bottom:12px}.header h1{font-size:clamp(26px,3vw,34px);line-height:1.2;margin:0}.box{background:#fff;border:1px solid #e7e9f1;border-radius:16px;padding:30px;box-shadow:0 8px 26px #1b224006}.acoes{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-top:25px}.acoes a,.acoes button{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:10px;padding:12px 18px;font:inherit;font-size:12px;font-weight:700;cursor:pointer;text-decoration:none}.principal{background:#6664df;color:#fff}.principal:hover{background:#5351c7}.secundario,.cancelar{background:#efeeff;color:#5653c4}.secundario:hover,.cancelar:hover{background:#e3e1ff}.erro,.sucesso{border-radius:10px;padding:14px 16px;margin-bottom:20px;font-size:13px}.erro{background:#fff1f2;color:#9e2738;border:1px solid #ffd5dc}.sucesso{background:#ecfdf3;color:#187448;border:1px solid #c8efd9}@media(max-width:800px){main{padding:78px 20px 48px}}@media(max-width:580px){.box{padding:20px}}main{max-width:870px}.box p{margin:0;padding:15px 0;border-bottom:1px solid #eceef5;font-size:14px;line-height:1.5;overflow-wrap:anywhere}.box p strong{display:inline-block;min-width:95px;color:#777d93;font-size:12px}.box p[style]{color:#a42d3b!important;background:#fff5f6;border:1px solid #ffdde2;border-radius:10px;padding:15px;margin-top:24px!important}.acoes .danger{background:#b82f42;color:#fff}.acoes .danger:hover{background:#9f2335}
</style></head><body><?php include '../../includes/menu_secretaria.php';?><main><section class="header"><h1>Excluir <?php echo htmlspecialchars($tipos[$tipo]);?></h1></section><section class="box"><?php echo $mensagem;?><p><strong>Nome:</strong> <?php echo htmlspecialchars($registro['nome']);?></p><?php if(isset($registro['perfil'])):?><p><strong>Perfil:</strong> <?php echo htmlspecialchars($registro['perfil']);?></p><?php endif;?><?php if(isset($registro['rm'])):?><p><strong>RM:</strong> <?php echo htmlspecialchars($registro['rm']??'');?></p><p><strong>Turma:</strong> <?php echo htmlspecialchars($registro['turma_nome']??'');?></p><?php endif;?><?php if(isset($registro['email'])):?><p><strong>E-mail:</strong> <?php echo htmlspecialchars($registro['email']??'');?></p><?php endif;?><p style="margin-top:18px;color:#8a3030;">Confirma a exclusão deste registro?</p><form method="POST" class="acoes"><input type="hidden" name="tipo" value="<?php echo htmlspecialchars($tipo);?>"><input type="hidden" name="acao" value="<?php echo htmlspecialchars($acao);?>"><input type="hidden" name="turma" value="<?php echo $turma_origem;?>"><input type="hidden" name="id" value="<?php echo $id;?>"><button class="danger" name="confirmar" value="1" type="submit">Confirmar exclusão</button><a class="cancelar" href="consultas_secretaria.php?tipo=<?php echo urlencode($tipo);?>&acao=<?php echo urlencode($acao);?><?php echo $turma_origem?'&turma='.$turma_origem:'';?>">Cancelar</a></form></section></main></body></html>
