<?php
session_start();
require '../../includes/conexao.php';
require '../../includes/verificar_sessao.php';
verificar_perfil('Secretaria');
mysqli_report(MYSQLI_REPORT_OFF);
$tipos=['aluno'=>'Aluno','professor'=>'Professor','coordenacao'=>'Coordenação','secretaria'=>'Secretaria','turma'=>'Turma','disciplina'=>'Disciplina'];
$tipo=strtolower(trim($_GET['tipo']??$_POST['tipo']??''));$acao=strtolower(trim($_GET['acao']??$_POST['acao']??'deletar'));$id=intval($_GET['id']??$_POST['id']??0);$turma_origem=intval($_GET['turma']??$_POST['turma']??0);
if(!isset($tipos[$tipo])||$id<=0){header('Location: cadastros_secretaria.php');exit();}$mensagem='';
function executar($conexao,$sql,$tipos,$valores){$stmt=$conexao->prepare($sql);if(!$stmt)return false;$stmt->bind_param($tipos,...$valores);$ok=$stmt->execute();$stmt->close();return $ok;}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['confirmar'])){
    $conexao->begin_transaction();$ok=true;
    if($tipo==='aluno'){
        $stmt=$conexao->prepare('SELECT id_matricula FROM matricula WHERE id_aluno=?');$stmt->bind_param('i',$id);$stmt->execute();$result=$stmt->get_result();$ids=[];while($row=$result->fetch_assoc())$ids[]=(int)$row['id_matricula'];$stmt->close();
        foreach($ids as $id_matricula){$ok=executar($conexao,'DELETE FROM frequencia WHERE id_matricula=?','i',[$id_matricula])&&$ok;$ok=executar($conexao,'DELETE FROM nota WHERE id_matricula=?','i',[$id_matricula])&&$ok;}
        $ok=executar($conexao,'DELETE FROM resposta WHERE id_usuario=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM mensagem WHERE remetente=? OR destinatario=?','ii',[$id,$id])&&$ok;$ok=executar($conexao,'DELETE FROM matricula WHERE id_aluno=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM usuario WHERE id_usuario=? AND perfil="Aluno"','i',[$id])&&$ok;
    } elseif($tipo==='turma'){
        $stmt=$conexao->prepare('SELECT id_turma_disciplina FROM turma_disciplina WHERE id_turma=?');$stmt->bind_param('i',$id);$stmt->execute();$result=$stmt->get_result();$ids=[];while($row=$result->fetch_assoc())$ids[]=(int)$row['id_turma_disciplina'];$stmt->close();
        foreach($ids as $id_td){$ok=executar($conexao,'DELETE FROM horario WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM frequencia WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM nota WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;}
        $ok=executar($conexao,'DELETE FROM turma_disciplina WHERE id_turma=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM matricula WHERE id_turma=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM turma WHERE id_turma=?','i',[$id])&&$ok;
    } elseif($tipo==='disciplina'){
        $stmt=$conexao->prepare('SELECT id_turma_disciplina FROM turma_disciplina WHERE id_disciplina=?');$stmt->bind_param('i',$id);$stmt->execute();$result=$stmt->get_result();$ids=[];while($row=$result->fetch_assoc())$ids[]=(int)$row['id_turma_disciplina'];$stmt->close();
        foreach($ids as $id_td){$ok=executar($conexao,'DELETE FROM horario WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM frequencia WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM nota WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;}
        $ok=executar($conexao,'DELETE FROM turma_disciplina WHERE id_disciplina=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM professor_disciplina WHERE id_disciplina=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM disciplina WHERE id_disciplina=?','i',[$id])&&$ok;
    } elseif($tipo==='professor'){
        $stmt=$conexao->prepare('SELECT id_turma_disciplina FROM turma_disciplina WHERE id_professor=?');$stmt->bind_param('i',$id);$stmt->execute();$result=$stmt->get_result();$ids=[];while($row=$result->fetch_assoc())$ids[]=(int)$row['id_turma_disciplina'];$stmt->close();
        foreach($ids as $id_td){$ok=executar($conexao,'DELETE FROM horario WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM frequencia WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;$ok=executar($conexao,'DELETE FROM nota WHERE id_turma_disciplina=?','i',[$id_td])&&$ok;}
        $ok=executar($conexao,'DELETE FROM turma_disciplina WHERE id_professor=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM professor_disciplina WHERE id_professor=?','i',[$id])&&$ok;$ok=executar($conexao,'DELETE FROM mensagem WHERE remetente=? OR destinatario=?','ii',[$id,$id])&&$ok;$ok=executar($conexao,'DELETE FROM usuario WHERE id_usuario=? AND perfil="Professor"','i',[$id])&&$ok;
    } else {
        $perfil=$tipos[$tipo];$ok=executar($conexao,'DELETE FROM mensagem WHERE remetente=? OR destinatario=?','ii',[$id,$id])&&$ok;$ok=executar($conexao,'DELETE FROM usuario WHERE id_usuario=? AND perfil=?','is',[$id,$perfil])&&$ok;
    }
    if($ok){$conexao->commit();header('Location: consultas_secretaria.php?tipo='.urlencode($tipo).'&acao='.urlencode($acao).($turma_origem?'&turma='.$turma_origem:''));exit();}$conexao->rollback();$mensagem='<div class="erro">Não foi possível excluir. Existem dados relacionados que não podem ser removidos automaticamente.</div>';
}
if($tipo==='aluno'){$stmt=$conexao->prepare('SELECT u.nome,u.email,m.rm,t.nome AS turma_nome FROM usuario u LEFT JOIN matricula m ON m.id_aluno=u.id_usuario LEFT JOIN turma t ON t.id_turma=m.id_turma WHERE u.id_usuario=? AND u.perfil="Aluno"');}elseif(in_array($tipo,['professor','coordenacao','secretaria'],true)){$stmt=$conexao->prepare('SELECT nome,email,perfil FROM usuario WHERE id_usuario=? AND perfil=?');$perfil=$tipos[$tipo];$stmt->bind_param('is',$id,$perfil);}elseif($tipo==='turma'){$stmt=$conexao->prepare('SELECT nome,ano_letivo,periodo FROM turma WHERE id_turma=?');}else{$stmt=$conexao->prepare('SELECT nome,carga_horaria FROM disciplina WHERE id_disciplina=?');}if($tipo==='aluno'||$tipo==='turma'||$tipo==='disciplina')$stmt->bind_param('i',$id);$stmt->execute();$registro=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$registro){header('Location: consultas_secretaria.php?tipo='.urlencode($tipo).'&acao='.urlencode($acao));exit();}
?>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Secretaria | Deletar</title><style>*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f3f7fb;color:#1f2937}main{max-width:850px;margin:32px auto;padding:0 20px 40px}.header{background:linear-gradient(135deg,#0d3d70,#1d8ec6);color:#fff;border-radius:18px;padding:26px 28px;margin-bottom:24px}.header h1{margin:0;font-size:2rem}.box{background:#fff;border:1px solid #e2eaf5;border-radius:18px;padding:26px;box-shadow:0 10px 22px rgba(15,23,42,.04)}.box p{border-bottom:1px solid #edf2f9;padding:10px 0;margin:0}.acoes{display:flex;gap:12px;margin-top:22px}button,a{border:0;border-radius:10px;padding:12px 18px;font-weight:bold;text-decoration:none;cursor:pointer}.danger{background:#b3262f;color:#fff}.cancelar{background:#eaf3ff;color:#0b447d}.erro{background:#fee;color:#9d1c1c;padding:10px;border-radius:8px;margin-bottom:15px}</style></head><body><?php include '../../includes/menu_secretaria.php';?><main><section class="header"><h1>Excluir <?php echo htmlspecialchars($tipos[$tipo]);?></h1></section><section class="box"><?php echo $mensagem;?><p><strong>Nome:</strong> <?php echo htmlspecialchars($registro['nome']);?></p><?php if(isset($registro['perfil'])):?><p><strong>Perfil:</strong> <?php echo htmlspecialchars($registro['perfil']);?></p><?php endif;?><?php if(isset($registro['rm'])):?><p><strong>RM:</strong> <?php echo htmlspecialchars($registro['rm']??'');?></p><p><strong>Turma:</strong> <?php echo htmlspecialchars($registro['turma_nome']??'');?></p><?php endif;?><?php if(isset($registro['email'])):?><p><strong>E-mail:</strong> <?php echo htmlspecialchars($registro['email']??'');?></p><?php endif;?><p style="margin-top:18px;color:#8a3030;">Confirma a exclusão deste registro?</p><form method="POST" class="acoes"><input type="hidden" name="tipo" value="<?php echo htmlspecialchars($tipo);?>"><input type="hidden" name="acao" value="<?php echo htmlspecialchars($acao);?>"><input type="hidden" name="turma" value="<?php echo $turma_origem;?>"><input type="hidden" name="id" value="<?php echo $id;?>"><button class="danger" name="confirmar" value="1" type="submit">Confirmar exclusão</button><a class="cancelar" href="consultas_secretaria.php?tipo=<?php echo urlencode($tipo);?>&acao=<?php echo urlencode($acao);?><?php echo $turma_origem?'&turma='.$turma_origem:'';?>">Cancelar</a></form></section></main></body></html>
