<?php
session_start();
require '../../includes/conexao.php';
require '../../includes/verificar_sessao.php';
verificar_perfil('Secretaria');
$id_questionario=intval($_GET['id']??$_POST['id']??0); if($id_questionario<=0){header('Location: questionarios_secretaria.php');exit();}
$mensagem='';
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['excluir'])){
    $stmt=$conexao->prepare('SELECT COUNT(*) AS total FROM resposta r JOIN pergunta p ON p.id_pergunta=r.id_pergunta WHERE p.id_questionario=?');$stmt->bind_param('i',$id_questionario);$stmt->execute();$tem_respostas=(int)$stmt->get_result()->fetch_assoc()['total']>0;$stmt->close();
    if($tem_respostas){$mensagem='<div style="background:#fff4e5;color:#8a5a00;padding:10px;border-radius:8px;margin-bottom:15px;">O questionário não pode ser excluído porque já possui respostas enviadas.</div>';}else{$conexao->begin_transaction();$stmt=$conexao->prepare('SELECT id_pergunta FROM pergunta WHERE id_questionario=?');$stmt->bind_param('i',$id_questionario);$stmt->execute();$result=$stmt->get_result();$ids=[];while($row=$result->fetch_assoc()){$ids[]=(int)$row['id_pergunta'];}$stmt->close();$ok=true;if($ids){$stmt=$conexao->prepare('DELETE FROM alternativa WHERE id_pergunta=?');foreach($ids as $id_pergunta){$stmt->bind_param('i',$id_pergunta);$ok=$stmt->execute()&&$ok;}$stmt->close();}$stmt=$conexao->prepare('DELETE FROM pergunta WHERE id_questionario=?');$stmt->bind_param('i',$id_questionario);$ok=$stmt->execute()&&$ok;$stmt->close();$stmt=$conexao->prepare('DELETE FROM questionario WHERE id_questionario=?');$stmt->bind_param('i',$id_questionario);$ok=$stmt->execute()&&$ok;$stmt->close();if($ok){$conexao->commit();header('Location: questionarios_secretaria.php');exit();}$conexao->rollback();$mensagem='<div style="background:#fee;color:#9d1c1c;padding:10px;border-radius:8px;margin-bottom:15px;">Não foi possível excluir o questionário.</div>';}}
$stmt=$conexao->prepare('SELECT q.*,u.nome AS criador FROM questionario q JOIN usuario u ON u.id_usuario=q.criado_por WHERE q.id_questionario=?');$stmt->bind_param('i',$id_questionario);$stmt->execute();$questionario=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$questionario){header('Location: questionarios_secretaria.php');exit();}
$perguntas=[];$stmt=$conexao->prepare('SELECT id_pergunta,enunciado FROM pergunta WHERE id_questionario=? ORDER BY id_pergunta');$stmt->bind_param('i',$id_questionario);$stmt->execute();$result=$stmt->get_result();while($row=$result->fetch_assoc()){$perguntas[$row['id_pergunta']=$row['id_pergunta']]=$row;}$stmt->close();
$alternativas=[];if($perguntas){$ids=array_keys($perguntas);$placeholders=implode(',',array_fill(0,count($ids),'?'));$tipos_ids=str_repeat('i',count($ids));$stmt=$conexao->prepare("SELECT id_pergunta,texto FROM alternativa WHERE id_pergunta IN ($placeholders) ORDER BY id_alternativa");$stmt->bind_param($tipos_ids,...$ids);$stmt->execute();$result=$stmt->get_result();while($row=$result->fetch_assoc()){$alternativas[$row['id_pergunta']][]=$row['texto'];}$stmt->close();}
$respostas=[];$stmt=$conexao->prepare('SELECT u.id_usuario,u.nome,m.id_turma,t.nome AS turma_nome,p.enunciado,r.resposta FROM resposta r JOIN pergunta p ON p.id_pergunta=r.id_pergunta JOIN usuario u ON u.id_usuario=r.id_usuario LEFT JOIN matricula m ON m.id_aluno=u.id_usuario LEFT JOIN turma t ON t.id_turma=m.id_turma WHERE p.id_questionario=? ORDER BY u.nome,p.id_pergunta');$stmt->bind_param('i',$id_questionario);$stmt->execute();$result=$stmt->get_result();while($row=$result->fetch_assoc()){$respostas[$row['id_usuario']]['nome']=$row['nome'];$respostas[$row['id_usuario']]['turma']=$row['turma_nome']??'Sala não informada';$respostas[$row['id_usuario']]['itens'][]=$row;}$stmt->close();
?>
<!DOCTYPE html>
<html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Secretaria | Questionário</title><style>*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f3f6fb;color:#1f2937}main{max-width:1000px;margin:32px auto;padding:0 20px 40px}.header{background:linear-gradient(135deg,#0d3d70,#1b8ac0);color:#fff;border-radius:18px;padding:26px 28px;margin-bottom:24px}.header h1{margin:0;font-size:2rem}.panel{background:#fff;border:1px solid #e2eaf5;border-radius:18px;padding:22px;margin-bottom:20px;box-shadow:0 8px 20px rgba(15,23,42,.04)}.pergunta{padding:14px 0;border-bottom:1px solid #edf2f9}.pergunta:last-child{border-bottom:0}.pergunta strong{color:#123d70}.pergunta ul{margin:8px 0;padding-left:20px;color:#5e6979}.aluno{border:1px solid #e2eaf5;border-radius:12px;padding:16px;margin:12px 0}.aluno h3{margin:0 0 10px;color:#123d70}.acoes{display:flex;gap:10px}.danger,.voltar{border:0;border-radius:9px;padding:11px 16px;font-weight:bold;text-decoration:none;cursor:pointer}.danger{background:#b3262f;color:#fff}.voltar{background:#eaf3ff;color:#0b447d}</style></head><body><?php include '../../includes/menu_secretaria.php'; ?><main><section class="header"><h1><?php echo htmlspecialchars($questionario['titulo']); ?></h1><p><?php echo htmlspecialchars($questionario['descricao']??''); ?></p></section><?php echo $mensagem; ?><section class="panel"><h2>Perguntas</h2><?php foreach($perguntas as $pergunta): ?><div class="pergunta"><strong><?php echo htmlspecialchars($pergunta['enunciado']); ?></strong><?php if(!empty($alternativas[$pergunta['id_pergunta']])):?><ul><?php foreach($alternativas[$pergunta['id_pergunta']] as $alternativa): ?><li><?php echo htmlspecialchars($alternativa); ?></li><?php endforeach; ?></ul><?php endif; ?></div><?php endforeach; ?><?php if(!$perguntas): ?><p>Nenhuma pergunta preenchida.</p><?php endif; ?></section><section class="panel"><h2>Respostas enviadas</h2><?php if($respostas):foreach($respostas as $aluno): ?><div class="aluno"><h3><?php echo htmlspecialchars($aluno['nome'].' - '.$aluno['turma']); ?></h3><?php foreach($aluno['itens'] as $item): ?><p><strong><?php echo htmlspecialchars($item['enunciado']); ?></strong><br><?php echo nl2br(htmlspecialchars($item['resposta'])); ?></p><?php endforeach; ?></div><?php endforeach;else:?><p>Nenhuma resposta enviada.</p><?php endif; ?></section><section class="acoes"><a class="voltar" href="questionarios_secretaria.php">Voltar</a><form method="POST" onsubmit="return confirm('Confirma a exclusão deste questionário?');"><input type="hidden" name="id" value="<?php echo $id_questionario; ?>"><button class="danger" name="excluir" value="1">Excluir questionário</button></form></section></main></body></html>
