<?php
session_start();
require '../../includes/conexao.php';
require '../../includes/verificar_sessao.php';
verificar_perfil('Secretaria');
$pesquisa = trim($_GET['q'] ?? '');
$parametro = '%' . $pesquisa . '%';
$stmt = $conexao->prepare('SELECT q.id_questionario, q.titulo, q.descricao, q.data_criacao, u.nome AS criador FROM questionario q JOIN usuario u ON u.id_usuario=q.criado_por WHERE q.titulo LIKE ? ORDER BY q.data_criacao DESC');
$stmt->bind_param('s', $parametro); $stmt->execute(); $result=$stmt->get_result(); $questionarios=[]; while($row=$result->fetch_assoc()){$questionarios[]=$row;} $stmt->close();
?>
<!DOCTYPE html>
<html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Secretaria | Questionários</title>
<style>*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f3f6fb;color:#1f2937}main{max-width:1080px;margin:32px auto;padding:0 20px 40px}.cabecalho{background:linear-gradient(135deg,#0d3d70,#1b8ac0);color:#fff;border-radius:18px;padding:26px 28px;margin-bottom:24px}.cabecalho h1{margin:0;font-size:2rem}.filtros{background:#fff;border-radius:14px;padding:18px 20px;margin-bottom:22px;box-shadow:0 4px 12px rgba(0,0,0,.06);display:flex;gap:12px}.filtros input{flex:1;padding:10px 12px;border:1px solid #dfe8f4;border-radius:8px}.filtros button,.novo{background:#0d4a8f;color:#fff;border:0;border-radius:8px;padding:10px 16px;font-weight:bold;text-decoration:none;cursor:pointer}.lista{display:grid;gap:14px}.item{display:block;background:#fff;border:1px solid #e2eaf5;border-radius:14px;padding:18px 20px;text-decoration:none;color:#1f2937;box-shadow:0 7px 18px rgba(15,23,42,.04)}.item h2{margin:0 0 7px;color:#123d70;font-size:1.15rem}.item p{margin:4px 0;color:#657286}.vazio{background:#fff;padding:30px;border-radius:14px;color:#666}</style></head><body><?php include '../../includes/menu_secretaria.php'; ?><main><section class="cabecalho"><h1>Questionários</h1></section><div class="filtros"><a class="novo" href="criar_questionario_secretaria.php">Criar novo questionário</a><form method="GET" style="display:flex;gap:10px;flex:1"><input name="q" placeholder="Pesquisar pelo título" value="<?php echo htmlspecialchars($pesquisa); ?>"><button type="submit">Pesquisar</button></form></div><?php if($questionarios): ?><section class="lista"><?php foreach($questionarios as $q): ?><a class="item" href="questionario_secretaria.php?id=<?php echo $q['id_questionario']; ?>"><h2><?php echo htmlspecialchars($q['titulo']); ?></h2><p><?php echo htmlspecialchars($q['descricao'] ?? ''); ?></p><p><?php echo htmlspecialchars($q['criador']); ?> - <?php echo date('d/m/Y',strtotime($q['data_criacao'])); ?></p></a><?php endforeach; ?></section><?php else: ?><div class="vazio">Nenhum questionário encontrado.</div><?php endif; ?></main></body></html>
