<?php
session_start();
require '../../includes/conexao.php';
require '../../includes/verificar_sessao.php';
verificar_perfil('Professor');
$id = $_SESSION['id_usuario'];
$stmt = $conexao->prepare('SELECT * FROM usuario WHERE id_usuario=? AND perfil="Professor" AND ativo=1');
$stmt->bind_param('i', $id); $stmt->execute(); $professor = $stmt->get_result()->fetch_assoc(); $stmt->close();
if (!$professor) { header('Location: inicio_professor.php'); exit(); }
function mostrar($campo, $valor) { echo '<div class="campo"><label>'.htmlspecialchars($campo, ENT_QUOTES, 'UTF-8').'</label><div class="valor">'.htmlspecialchars((string)($valor ?? '—'), ENT_QUOTES, 'UTF-8').'</div></div>'; }
?>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Professor | Cadastro — Instituto Atlas</title><style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');*{box-sizing:border-box}body{margin:0;background:#f7f8fc;color:#202338;font-family:Inter,Arial,sans-serif}.atlas-main{max-width:1320px;margin:0 auto;padding:36px 60px 76px}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.15em;color:#777d93;text-transform:uppercase}.head{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:30px}.head h1{font-size:38px;letter-spacing:-.055em;margin:13px 0 8px;font-weight:800}.head h1 span{color:#6664df}.sub{color:#777d93;font-size:14px;line-height:1.6;margin:0}.tag{border:1px solid #e7e9f1;background:#fff;border-radius:30px;padding:10px 15px;font-size:12px;color:#6664df;font-weight:700}.box{background:#fff;border:1px solid #e7e9f1;border-radius:17px;padding:28px 30px;margin-bottom:20px;box-shadow:0 7px 22px rgba(29,32,63,.025)}.box-head{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:23px}.box h2{font-size:17px;letter-spacing:-.03em;margin:0}.box small{font-size:12px;color:#777d93}.notice{background:#f0efff;border:1px solid #e7e4ff;border-radius:12px;padding:15px 18px;color:#514dc3;font-size:13px;margin-bottom:22px;line-height:1.5}.formulario{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:21px}.campo{min-width:0}.campo label{display:block;color:#777d93;font-size:12px;font-weight:700;margin-bottom:9px}.valor{min-height:45px;display:flex;align-items:center;border:1px solid #e7e9f1;border-radius:10px;padding:11px 14px;background:#fafbfe;font-size:13px;color:#292d45;overflow-wrap:anywhere}.perfil{display:flex;align-items:center;gap:16px;padding:20px 23px;background:#fbfbff;border:1px solid #e7e9f1;border-radius:13px;margin-bottom:25px}.avatar{width:50px;height:50px;flex:none;border-radius:14px;background:#6664df;color:#fff;display:grid;place-items:center;font-weight:800;font-size:20px}.perfil strong{display:block;font-size:15px;margin-bottom:5px}.perfil p{margin:0;font-size:12px;color:#777d93}@media(max-width:1100px){.atlas-main{padding:32px 30px 65px}}@media(max-width:700px){.atlas-main{padding:28px 18px 50px}.head h1{font-size:31px}.tag{display:none}.box{padding:22px 18px}.formulario{grid-template-columns:1fr}.box-head{align-items:flex-start;flex-direction:column}}
</style></head><body><?php include '../../includes/menu_professor.php'; ?><main class="atlas-main"><header class="head"><div><div class="eyebrow">Instituto Atlas &nbsp;/&nbsp; Portal do professor</div><h1>Meu cadastro<span>.</span></h1><p class="sub">Consulte suas informações pessoais e de contato.</p></div><span class="tag">Área do professor</span></header><div class="notice">Este cadastro é somente para consulta. Para atualizar seus dados, entre em contato com a secretaria.</div><section class="box"><div class="perfil"><div class="avatar"><?php echo htmlspecialchars(substr($professor['nome'] ?? 'P',0,1),ENT_QUOTES,'UTF-8'); ?></div><div><strong><?php echo htmlspecialchars($professor['nome'] ?? 'Professor',ENT_QUOTES,'UTF-8'); ?></strong><p>Professor · Instituto Atlas</p></div></div><div class="box-head"><h2>Dados pessoais</h2><small>Informações cadastradas</small></div><div class="formulario"><?php mostrar('Perfil',$professor['perfil']);mostrar('Nome completo',$professor['nome']);mostrar('CPF',$professor['cpf']);mostrar('RG',$professor['rg']);mostrar('Data de nascimento',$professor['data_nascimento']);?></div></section><section class="box"><div class="box-head"><h2>Contato</h2><small>Informações de contato</small></div><div class="formulario"><?php mostrar('Telefone',$professor['telefone']);mostrar('E-mail',$professor['email']);mostrar('Endereço',$professor['endereco']);?></div></section></main></body></html>